/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 10-3月-2020 00:46:23 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `book` CASCADE
;

DROP TABLE IF EXISTS `bookclass` CASCADE
;

DROP TABLE IF EXISTS `order` CASCADE
;

DROP TABLE IF EXISTS `orderDetail` CASCADE
;

DROP TABLE IF EXISTS `shopcar` CASCADE
;

DROP TABLE IF EXISTS `stock` CASCADE
;

DROP TABLE IF EXISTS `usr` CASCADE
;

/* Create Tables */

CREATE TABLE `book`
(
	`ord` BIGINT NOT NULL AUTO_INCREMENT,
	`bookName` VARCHAR(200) NOT NULL,
	`ISBN` VARCHAR(50) NOT NULL,
	`price` DECIMAL(10,4) NULL,
	`press` VARCHAR(200) NOT NULL,
	`bookClass` BIGINT NOT NULL,
	`mark` VARCHAR(500) NULL,
	`picture` VARCHAR(200) NOT NULL,
	`createTime` DATETIME NULL,
	CONSTRAINT `PK_book` PRIMARY KEY (`ord` ASC)
)

;

CREATE TABLE `bookclass`
(
	`ord` BIGINT NOT NULL AUTO_INCREMENT,
	`className` VARCHAR(50) NOT NULL,
	`mark` VARCHAR(50) NULL,
	`createTime` DATETIME NOT NULL,
	CONSTRAINT `PK_bookclass` PRIMARY KEY (`ord` ASC)
)

;

CREATE TABLE `order`
(
	`ord` BIGINT NOT NULL AUTO_INCREMENT,
	`orderCode` VARCHAR(50) NOT NULL,
	`userOrd` BIGINT NULL,
	`status` INT NULL DEFAULT 0,
	`totalNum` INT NULL DEFAULT 0,
	`totalPrice` DECIMAL(10,4) NULL DEFAULT 0,
	`createTime` DATETIME NOT NULL,
	CONSTRAINT `PK_order` PRIMARY KEY (`ord` ASC)
)

;

CREATE TABLE `orderDetail`
(
	`ord` BIGINT NOT NULL AUTO_INCREMENT,
	`orderOrd` BIGINT NOT NULL,
	`bookOrd` BIGINT NOT NULL,
	`bookName` VARCHAR(200) NOT NULL,
	`ISBN` VARCHAR(50) NULL,
	`bookPrice` DECIMAL(10,4) NOT NULL,
	`bookPress` VARCHAR(200) NULL,
	CONSTRAINT `PK_orderDetail` PRIMARY KEY (`ord` ASC)
)

;

CREATE TABLE `shopcar`
(
	`ord` BIGINT NOT NULL AUTO_INCREMENT,
	`userId` BIGINT NOT NULL,
	`bookId` BIGINT NOT NULL,
	`num` INT NOT NULL,
	`createTime` DATETIME NULL,
	CONSTRAINT `PK_shopcar` PRIMARY KEY (`ord` ASC)
)

;

CREATE TABLE `stock`
(
	`ord` BIGINT NOT NULL AUTO_INCREMENT,
	`stockNum` INT NOT NULL DEFAULT 0,
	`bookOrd` BIGINT NOT NULL,
	CONSTRAINT `PK_stock` PRIMARY KEY (`ord` ASC)
)

;

CREATE TABLE `usr`
(
	`ord` BIGINT NOT NULL AUTO_INCREMENT,
	`phone` VARCHAR(50) NOT NULL,
	`username` VARCHAR(200) NOT NULL,
	`pass` VARCHAR(200) NOT NULL,
	`role` INT NULL DEFAULT 0,
	`balance` DECIMAL(10,4) NOT NULL DEFAULT 0,
	`createTime` DATETIME NULL,
	CONSTRAINT `PK_user` PRIMARY KEY (`ord` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `book` 
 ADD INDEX `IXFK_book_bookclass` (`bookClass` ASC)
;

ALTER TABLE `order` 
 ADD INDEX `IXFK_order_user` (`userOrd` ASC)
;

ALTER TABLE `orderDetail` 
 ADD INDEX `IXFK_orderDetail_book` (`bookOrd` ASC)
;

ALTER TABLE `orderDetail` 
 ADD INDEX `IXFK_orderDetail_order` (`orderOrd` ASC)
;

ALTER TABLE `shopcar` 
 ADD INDEX `IXFK_shopcar_book` (`bookId` ASC)
;

ALTER TABLE `shopcar` 
 ADD INDEX `IXFK_shopcar_user` (`userId` ASC)
;

ALTER TABLE `stock` 
 ADD INDEX `IXFK_stock_book` (`bookOrd` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `book` 
 ADD CONSTRAINT `FK_book_bookclass`
	FOREIGN KEY (`bookClass`) REFERENCES `bookclass` (`ord`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `order` 
 ADD CONSTRAINT `FK_order_user`
	FOREIGN KEY (`userOrd`) REFERENCES usr (`ord`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `orderDetail` 
 ADD CONSTRAINT `FK_orderDetail_book`
	FOREIGN KEY (`bookOrd`) REFERENCES `book` (`ord`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `orderDetail` 
 ADD CONSTRAINT `FK_orderDetail_order`
	FOREIGN KEY (`orderOrd`) REFERENCES `order` (`ord`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `shopcar` 
 ADD CONSTRAINT `FK_shopcar_book`
	FOREIGN KEY (`bookId`) REFERENCES `book` (`ord`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `shopcar` 
 ADD CONSTRAINT `FK_shopcar_user`
	FOREIGN KEY (`userId`) REFERENCES usr (`ord`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `stock` 
 ADD CONSTRAINT `FK_stock_book`
	FOREIGN KEY (`bookOrd`) REFERENCES `book` (`ord`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1
; 
